Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "DontZap" "false"
EndSection

Section "Device"
    Identifier "Mediatek DRM"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card1"
EndSection

Section "Monitor"
    Identifier "mon"
EndSection

Section "Screen"
    Identifier "scr"
    Device "Mediatek DRM"
    Monitor "mon"
    DefaultDepth 16
    SubSection "Display"
        Depth 16
    EndSubSection
EndSection

Section "InputDevice"
    Identifier "touch"
    Driver "evdev"
    Option "Device" "/dev/input/event0"
    Option "CorePointer" "true"
EndSection

Section "ServerLayout"
    Identifier "layout"
    Screen "scr"
    InputDevice "touch"
EndSection
